services:
  jenkins:
    build: .
    container_name: jenkins
    user: root
    restart: unless-stopped
    ports:
      - "9090:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
    environment:
      - TZ=Asia/Ho_Chi_Minh